# Generated by Django 3.1.2 on 2020-10-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('orders', '0002_auto_20201005_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offers',
            field=models.ManyToManyField(to='offers.Offer'),
        ),
    ]
