# Generated by Django 3.1.2 on 2020-10-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=13),
        ),
    ]
